packages:
    - ./package
    - ./tests/*
    - ./examples/*

catalogs:
    dev:
        "@types/node": ^25
        "tsdown": 0.18.1
    peer:
        "tsdown": ~0.18.0
    test:
        "vitest": ^4

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
