packages:
    - ./package
    - ./tests/*
    - ./examples/*

catalogs:
    dev:
        "@types/node": ^25
        # Minimum supported version
        "tsdown": 0.18.0
    peer:
        # Supported versions
        "tsdown": ~0.18.0
    test:
        "vitest": ^4

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
